"""Pseudonymous ID generation (spec sections 8/17).

    Participant: P001, P002, ...
    Session DB ID: P023_S01, P023_S02, ... (disk folder is S01, S02, ...)

Readable v0.9 trial identities are allocated in ``core.data_naming`` as
condition T##/TR## + attempt R##. ``generate_trial_id`` remains only for
backward compatibility with older tests/data utilities.

All IDs are generated by looking at the *experimental* database only
(never the identifiable one) so this logic has no way to leak PII even by
accident.
"""

from __future__ import annotations

import re

from core.database import Database
from models.enums import WorkflowStep

_PARTICIPANT_RE = re.compile(r"^P(\d{3,})$")
_SESSION_RE = re.compile(r"^S(\d{2,})$")
_TRIAL_RE = re.compile(r"^T(\d{3,})$")
_RUN_RE = re.compile(r"^R(\d{2,})$")

_STEP_SHORT_CODE = {
    WorkflowStep.REGISTRATION: "REG",
    WorkflowStep.STUDY1_TRAINING: "S1TR",
    WorkflowStep.STUDY1_STUDY: "S1ST",
    WorkflowStep.STUDY2_TRAINING: "S2TR",
    WorkflowStep.STUDY2_STUDY: "S2ST",
    WorkflowStep.AGENT_OBSERVATION: "OBS",
}


def generate_participant_code(db: Database) -> str:
    """Next unused P### code, based on the highest existing code."""
    rows = db.experimental_conn.execute(
        "SELECT participant_code FROM participants"
    ).fetchall()
    max_n = 0
    for row in rows:
        match = _PARTICIPANT_RE.match(row["participant_code"])
        if match:
            max_n = max(max_n, int(match.group(1)))
    return f"P{max_n + 1:03d}"


def generate_session_id(db: Database, participant_code: str) -> str:
    """Next unused session ID for this participant, e.g. 'P023_S02'."""
    rows = db.experimental_conn.execute(
        "SELECT session_id FROM sessions WHERE participant_code = ?",
        (participant_code,),
    ).fetchall()
    max_n = 0
    prefix = f"{participant_code}_S"
    for row in rows:
        session_id = row["session_id"]
        if session_id.startswith(prefix):
            match = _SESSION_RE.match(session_id[len(prefix) - 1 :])
            if match:
                max_n = max(max_n, int(match.group(1)))
    return f"{participant_code}_S{max_n + 1:02d}"


def generate_trial_id(db: Database, session_id: str) -> str:
    """Next unused trial ID for this session, e.g. 'P023_S01_T004'."""
    rows = db.experimental_conn.execute(
        "SELECT trial_id FROM trials WHERE session_id = ?",
        (session_id,),
    ).fetchall()
    max_n = 0
    prefix = f"{session_id}_T"
    for row in rows:
        trial_id = row["trial_id"]
        if trial_id.startswith(prefix):
            match = _TRIAL_RE.match(trial_id[len(prefix) - 1 :])
            if match:
                max_n = max(max_n, int(match.group(1)))
    return f"{session_id}_T{max_n + 1:03d}"


def generate_run_id(db: Database, participant_code: str, step: WorkflowStep) -> str:
    """Next unused run ID for this participant+step, e.g. 'P023_S1TR_R02'.

    Repeats of the same step for the same participant get an incrementing
    run number, so "do training three times" naturally produces
    P023_S1TR_R01, P023_S1TR_R02, P023_S1TR_R03.
    """
    short_code = _STEP_SHORT_CODE[step]
    prefix = f"{participant_code}_{short_code}_R"
    rows = db.experimental_conn.execute(
        "SELECT run_id FROM workflow_runs WHERE participant_code = ? AND step = ?",
        (participant_code, step.value),
    ).fetchall()
    max_n = 0
    for row in rows:
        run_id = row["run_id"]
        if run_id.startswith(prefix):
            match = _RUN_RE.match(run_id[len(prefix) - 1 :])
            if match:
                max_n = max(max_n, int(match.group(1)))
    return f"{prefix}{max_n + 1:02d}"
